import type { MessageSchema } from './en'

export const zhCN: MessageSchema = {
  app: { name: '库存艺管', shortName: '艺库', tagline: '让每件作品有序流转。', workspace: '运营工作台' },
  nav: { overview: '概览', operations: '业务操作', management: '管理中心', dashboard: '仪表盘', products: '商品', inventory: '库存', orders: '订单', imports: 'SumUp 导入', reports: '报表', profile: '个人资料与语言', tenants: '租户', users: '用户', audit: '审计日志', globalData: '全局数据', collapse: '收起导航', expand: '展开导航', openMenu: '打开导航' },
  common: { add: '添加', create: '创建', edit: '编辑', delete: '删除', cancel: '取消', close: '关闭', save: '保存更改', saving: '正在保存…', confirm: '确认', continue: '继续', back: '返回', retry: '重试', refresh: '刷新', search: '搜索', filter: '筛选', reset: '重置', export: '导出 CSV', download: '下载', upload: '上传', actions: '操作', details: '详情', status: '状态', date: '日期', name: '名称', email: '邮箱', role: '角色', tenant: '租户', all: '全部', yes: '是', no: '否', enabled: '已启用', disabled: '已禁用', active: '在售', inactive: '停用', optional: '可选', loading: '加载中…', noData: '暂无数据', noResults: '没有匹配结果', pageOf: '第 {page} 页，共 {pages} 页', items: '共 {count} 项', created: '创建时间', updated: '更新时间', view: '查看', clear: '清除' },
  auth: { signIn: '登录', signOut: '退出登录', welcome: '欢迎回来', instruction: '使用工作账号进入库存工作台。', email: '用户名', password: '密码', emailPlaceholder: '请输入用户名', passwordPlaceholder: '请输入密码', signingIn: '正在登录…', secureSession: '采用轮换刷新令牌保护会话', loginFailed: '用户名或密码不正确。' },
  dashboard: { eyebrow: '今日概览', title: '库存也有脉搏。', subtitle: '及时掌握销售、库存流转和待处理事项，避免小问题变成大麻烦。', revenue: '销售额', openOrders: '待处理订单', lowStock: '低库存商品', unitsOnHand: '现有库存', salesTrend: '销售节奏', lastSevenDays: '最近 7 天', stockAttention: '库存预警', stockAttentionHint: '已达到或低于补货阈值的商品', recentOrders: '最近订单', quickActions: '快捷操作', newOrder: '创建订单', adjustStock: '调整库存', importSumUp: '导入 SumUp 文件', healthy: '库存覆盖情况良好', source: '来源' },
  products: { eyebrow: '商品目录', title: '商品', subtitle: '在同一目录管理价格、成本、图片与库存标识。', addProduct: '添加商品', editProduct: '编辑商品', createProduct: '创建商品', sku: 'SKU', productName: '商品名称', category: '分类', artistName: '艺术家或制作者', description: '描述', price: '销售价格', costPrice: '成本价', currency: '币种', stock: '当前库存', threshold: '低库存阈值', image: '图片', imageHint: '支持 JPG、PNG 或 WebP，最大 10 MB', activity: '销售状态', deleteTitle: '删除商品？', deleteBody: '将从在售目录移除 {name}，已有订单记录仍会保留。', created: '商品已创建。', saved: '商品已更新。', deleted: '商品已删除。', emptyTitle: '创建商品目录', emptyBody: '添加首件商品即可开始追踪库存与销售。', searchPlaceholder: '按名称或 SKU 搜索', salesHistory: '销售记录', unitsSoldValue: '已售 {count}', neverSold: '暂无销售' },
  inventory: { eyebrow: '库存台账', title: '库存', subtitle: '每次调整都有记录，当前库存始终可以追溯到具体流水。', adjust: '调整库存', product: '商品', movement: '变动', quantity: '数量', stockBefore: '调整前', stockAfter: '调整后', reason: '原因', actor: '操作人', selectProduct: '选择商品', adjustmentType: '调整方式', addStock: '增加库存', removeStock: '减少库存', setStock: '设置准确库存', quantityHint: '请输入正整数', reasonPlaceholder: '请填写库存变动原因', adjusted: '库存已调整。', insufficient: '该调整会导致库存为负数。', emptyTitle: '暂无库存流水', emptyBody: '调整商品库存或确认订单后，流水将显示在这里。', movementTypes: { MANUAL_ADJUSTMENT: '手动调整', ORDER_CONFIRMED: '订单确认', ORDER_CANCELLED: '订单取消', REFUND: '退款', SUMUP_IMPORT: 'SumUp 导入', IMPORT_REVERTED: '撤销导入' } },
  orders: { eyebrow: '销售工作台', title: '订单', subtitle: '从草稿、确认、完成到退款，每一步都保留库存轨迹。', newOrder: '新建订单', createOrder: '创建订单', orderNumber: '订单号', customer: '客户', customerName: '客户姓名', customerEmail: '客户邮箱', orderedAt: '下单日期', total: '合计', channel: '渠道', channels: { exhibition: '展会', online: '线上', sumup: 'SumUp', other: '其他' }, source: '来源', notes: '备注', items: '订单商品', addItem: '添加商品', product: '商品', quantity: '数量', unitPrice: '单价', lineTotal: '小计', confirmOrder: '确认订单', completeOrder: '完成订单', cancelOrder: '取消订单', refundOrder: '订单退款', refundTitle: '退还所有剩余商品？', refundBody: '可退款数量将恢复库存，并记录退款明细。', confirmTitle: '确认此订单？', confirmBody: '系统将扣减每项商品库存，并记录库存流水。', cancelTitle: '取消此订单？', cancelBody: '此前扣减的库存将返还。', created: '订单草稿已创建。', confirmed: '订单已确认并扣减库存。', completed: '订单已完成。', cancelled: '订单已取消并恢复库存。', refunded: '退款已记录。', emptyTitle: '暂无订单', emptyBody: '创建订单或导入 SumUp 文件即可开始积累销售记录。', filters: { all: '全部订单', draft: '草稿', active: '处理中', completed: '已完成', cancelled: '已取消' } },
  import: { eyebrow: 'SumUp 工作区', title: '导入 SumUp 数据', listTitle: 'SumUp 导入', subtitle: '任何数据影响订单或库存前，都可以逐行确认。', newImport: '新建导入', file: '文件', type: '识别类型', rows: '行数', progress: '进度', started: '开始时间', stepUpload: '上传', stepColumns: '列映射', stepProducts: '匹配商品', stepReview: '复核', stepResult: '结果', dropTitle: '将 SumUp 导出文件拖到这里', dropBody: '或选择不超过 20 MB 的 CSV、XLS、XLSX 文件', chooseFile: '选择文件', selectedFile: '已选文件', uploadAndAnalyze: '上传并分析', analyzing: '正在分析文件…', mappingHint: '确认源文件列与销售字段的对应关系。', sourceColumn: '源文件列', targetField: '库存系统字段', sample: '示例值', unmapped: '不导入', transactionId: '交易 ID', orderNumber: '订单号', transactionDate: '交易日期', amount: '金额', currency: '币种', productName: '商品名称', productSku: '商品 SKU', quantity: '数量', fee: '手续费', productMatchHint: '处理无法通过 SKU 或准确名称匹配的商品。', sourceProduct: '源商品', matchedProduct: '库存商品', keepUnallocated: '保留为待分配', impactTitle: '导入影响', impactOrders: '将创建的订单', impactTransactions: '交易数', impactStock: '库存流水', impactErrors: '错误行', row: '行', normalizedPreview: '标准化数据预览', applySummaryInventory: '同时从库存扣减已映射商品的汇总数量', summaryInventoryTitle: '把商品汇总应用到库存？', summaryInventoryBody: '这是第二次明确确认。系统将扣减映射后的汇总数量，并生成库存流水。', applyInventory: '应用到库存', reviewWarning: '确认前请检查未匹配商品和库存影响。', confirmImport: '确认导入', importing: '正在导入数据…', completedTitle: '导入完成', completedBody: '已导入 {count} 行。你可以查看错误或返回导入历史。', importedRows: '新增', updatedRows: '更新', duplicateRows: '重复', skippedRows: '跳过', viewImports: '查看导入历史', downloadErrors: '下载错误 CSV', revert: '撤销导入', revertTitle: '撤销此次导入？', revertBody: '系统将反向生成库存流水；导入后被人工修改的记录会阻止撤销。', duplicate: '这个文件已上传过。', noFile: '请先选择文件。', emptyTitle: '暂无 SumUp 导入', emptyBody: '上传导出文件，将外部销售与商品目录核对。' },
  reports: { eyebrow: '销售分析', title: '报表', subtitle: '每笔销售只统计一次，并按币种与来源清晰拆分。', dateRange: '日期范围', last30Days: '最近 30 天', revenue: '净销售额', orders: '订单数', unitsSold: '售出数量', grossProfit: '估算毛利润', pending: '待分配销售', grossSales: '毛销售额', discounts: '折扣', refunds: '退款', fees: 'SumUp 手续费', afterFees: '扣除手续费后', productCost: '估算商品成本', averageOrderValue: '平均订单金额', successfulPayments: '成功支付数', financialDetails: '财务对账明细', estimatedGrossProfitHint: '净销售额减去商品当前成本价', dailySales: '每日销售', topProducts: '热销商品', salesSources: '销售来源', product: '商品', units: '数量', channels: '销售渠道', paymentMethods: '支付方式', events: '展会或活动', allTenants: '全部租户', unspecified: '未指定', labels: { MANUAL: '手动订单', SUMUP_IMPORT: 'SumUp 导入', EXHIBITION: '展会', ONLINE: '线上', SUMUP: 'SumUp', OTHER: '其他', CASH: '现金', CARD: '银行卡', PAYPAL: 'PayPal', BANK_TRANSFER: '银行转账' }, noExchange: '不同币种分别展示，不进行汇率换算。', noData: '所选日期范围内暂无已完成销售。' },
  profile: { eyebrow: '个人设置', title: '个人资料与语言', subtitle: '界面语言会随账号同步到所有设备；业务币种和时区仍由租户设置决定。', identity: '身份信息', displayName: '显示名称', email: '邮箱地址', language: '界面语言', languageHint: '保存后，导航、表单、消息和日期会立即切换语言。', english: 'English', chinese: '简体中文', french: 'Français', tenantSettings: '业务格式', timezone: '时区', currency: '默认币种', businessLocale: '业务区域', saved: '个人资料和语言已保存。' },
  admin: { tenantsTitle: '租户', tenantsSubtitle: '管理相互隔离的业务空间及其格式规则。', addTenant: '添加租户', editTenant: '编辑租户', tenantName: '租户名称', slug: '标识', currency: '币种', timezone: '时区', businessLocale: '业务区域', usersCount: '用户数', usersTitle: '用户', usersSubtitle: '管理访问权限、角色、租户归属和账号状态。', addUser: '添加用户', editUser: '编辑用户', username: '用户名', displayName: '显示名称', temporaryPassword: '临时密码', preferredLanguage: '首选语言', disableUser: '禁用用户', enableUser: '启用用户', auditTitle: '审计日志', auditSubtitle: '查看跨租户的敏感操作和管理员访问记录。', action: '操作', entity: '对象', actor: '操作人', ipAddress: 'IP 地址', timestamp: '时间', globalTitle: '全局数据', globalSubtitle: '跨租户查看商品、订单、交易和导入记录。', dataType: '数据类型', products: '商品', orders: '订单', transactions: '外部交易', imports: '导入', crossTenantNotice: '管理员对全局数据的访问会记录在审计日志中。', created: '记录已创建。', saved: '记录已更新。' },
  status: { DRAFT: '草稿', CONFIRMED: '已确认', COMPLETED: '已完成', CANCELLED: '已取消', REFUNDED: '已退款', PARTIALLY_REFUNDED: '部分退款', UNALLOCATED: '待分配', UPLOADED: '已上传', ANALYZING: '分析中', READY: '待确认', READY_FOR_MAPPING: '待映射', READY_FOR_CONFIRMATION: '待确认导入', IMPORTING: '导入中', COMPLETED_WITH_ERRORS: '完成但有错误', FAILED: '失败', REVERTED: '已撤销', REVERSED: '已反向撤销', ENABLED: '已启用', DISABLED: '已禁用' },
  errors: { title: '需要处理的问题', generic: '请求未能完成，请重试。', network: '无法连接服务，请检查网络后重试。', forbidden: '你没有执行此操作的权限。', notFound: '找不到页面', notFoundBody: '页面可能已移动或不再存在。', returnDashboard: '返回仪表盘', validation: '请检查标记的字段。', conflict: '编辑期间记录已发生变化，请刷新后重试。', duplicateSku: '此 SKU 已在当前工作区使用。', insufficientStock: '库存不足，无法完成此操作。', currencyMismatch: '商品币种必须与订单币种一致。', invalidLocale: '请选择英文、简体中文或法语。', sessionExpired: '会话已过期，请重新登录。' },
  validation: { required: '请填写{field}。', email: '请输入有效的邮箱地址。', positive: '请输入大于零的数字。', nonNegative: '请输入零或正数。', passwordLength: '密码至少需要 10 个字符。', fileSize: '所选文件过大。', fileType: '请选择支持的文件类型。' },
}
