package com.inventoryart.inventory;
public enum MovementType { INITIAL, PURCHASE, SALE, RETURN, ADJUSTMENT_IN, ADJUSTMENT_OUT, STOCK_CORRECTION, ORDER_CANCEL, ORDER_REFUND, SUMUP_IMPORT, SUMUP_REVERSAL }

